# https://circleci.com/orbs/registry/orb/circleci/node
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Environment Details
          command: "echo 'Node.js version: $(node -v)\n' && echo 'npm version: $(npm -v)"
      - node/install-packages
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Semantic Release
          command: npm run semantic-release || true
orbs:
  node: circleci/node@4.7.0
version: 2.1
