# https://circleci.com/orbs/registry/orb/circleci/node
jobs:
  build:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run test
      - run: npm run semantic-release || true
orbs:
  node: circleci/node@4.7.0
version: 2.1
