# https://circleci.com/orbs/registry/orb/circleci/node
version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout
      - node/install
      - run:
          name: Environment Details
          command: |
            echo "Node.js version"
            node --version
            echo "npm version"
            npm --version
      - node/install-packages
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Semantic Release
          command: npm run semantic-release || true
