# https://circleci.com/orbs/registry/orb/circleci/node
jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Semantic Release
          command: npm run semantic-release || true
orbs:
  node: circleci/node@4.7.0
version: 2.1
